name: project-run
description: Executar projeto python
supported-os:
- windows
- linux
- mac
requirements-check:
  dependency-python:
    check-command: python3 --version
    info: python is not installed
command:
  linux: |
    #!/usr/bin/bash
    source {{ target_path }}/.venv/bin/activate
    python3 {{ target_path }}/local.py
  mac: |
    #!/usr/bin/bash
    source {{ target_path }}/.venv/bin/activate
    python3 {{ target_path }}/local.py
  windows: |
    venv/Scripts/activate
    python3 {{ target_path }}\local.py
